version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/breaddatabase
      SPRING_DATASOURCE_USERNAME: PoliteBear
      SPRING_DATASOURCE_PASSWORD: BraveVolunteer365

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: PoliteBear
      POSTGRES_PASSWORD: BraveVolunteer365
      POSTGRES_DB: breaddatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
